name: Black

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: gha-runners-smartweb
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4
    - name: Run check
      uses: plone/code-analysis-action@v2
      with:
        base_dir: 'src'
        check: 'black'
        path: |
          imio/smartweb/core