name: Black

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: gha-runners-smartweb
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4
    - name: Run check
      uses: IMIO/gha/code-analysis-notify@main
      with:
        BASE_DIR: 'src'
        CHECK: 'black'
        PATH: |
          imio/smartweb/core
        MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}