name: Coverage

on:
  workflow_dispatch:

jobs:
  test:
    runs-on:
      group: 'self-hosted'
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4
    - name: Run check
      uses: IMIO/gha/plone-package-test-notify@main
      with:
        TEST_COMMAND: TZ=UTC coverage run bin/test
        REQUIREMENTS_FILE: 'requirements-coverage.txt'
        MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
    - name: Submit to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo coveralls --service=github