# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run black
      run: black --check --verbose .

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Cache eggs
      uses: actions/cache@v2
      env:
        cache-name: cache-eggs
      with:
        path: ./eggs
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and run buildout
      run: |
        sudo apt update -qq -y
        sudo apt-get install -qq -y python3-dev
        sudo apt-get autoremove -qq -y
        sudo apt-get autoclean -qq -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install https://github.com/bboe/coveralls-python/archive/github_actions.zip
        buildout -Nt 5

    - name: Test
      run: |
        bin/test

    # - name: Coveralls
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     parallel: true

    - name: Coverage test
      run: |
        coverage run bin/test

    - name: Submit to Coveralls
      env:
        COVERALLS_PARALLEL: true
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
