name: Tests

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
#   black:
#     runs-on: gha-runners-smartweb
#     steps:
#     - name: Checkout codebase
#       uses: actions/checkout@v4
#     - name: Run check
#       uses: IMIO/gha/code-analysis-notify@v3.9.4
#       with:
#         BASE_DIR: 'src'
#         CHECK: 'black'
#         PATH: |
#           imio/smartweb/core
#         MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}

  test:
    runs-on: gha-runners-smartweb
    strategy:
      matrix:
        python-version: ['3.10', '3.13']
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4
    - name: Run check
      uses: IMIO/gha/plone-package-test-notify@setup-python-with-uv
      with:
        CACHE_KEY: eggs-test-${{ hashFiles('base.cfg') }}-python-${{ matrix.python-version }}
        INSTALL_DEPENDENCIES_COMMANDS: |
          uv venv --python ${{ matrix.python-version }}
          uv pip install -r requirements.txt
        MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
        PYTHON_VERSION: ${{ matrix.python-version }}
        TEST_COMMAND: TZ=UTC bin/test

#   coverage:
#     runs-on: gha-runners-smartweb
#     steps:
#     - name: Checkout codebase
#       uses: actions/checkout@v4
#     - name: Run check
#       uses: IMIO/gha/plone-package-test-notify@setup-python-with-uv
#       with:
#         CACHE_KEY: eggs-test-${{ hashFiles('base.cfg') }}-python-3.10
#         TEST_COMMAND: TZ=UTC coverage run bin/test
#         REQUIREMENTS_FILE: 'requirements-coverage.txt'
#         MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
#     - name: Submit to Coveralls
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       run: coveralls --service=github


