# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run black
      run: black --check --verbose .

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Cache eggs
      uses: actions/cache@v2
      env:
        cache-name: cache-eggs
      with:
        path: ./eggs
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and run buildout
      run: |
        sudo apt-get install -qq -y python3-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        buildout -Nt 5

    - name: Test
      run: |
        bin/test

  coverage:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Cache eggs
      uses: actions/cache@v2
      env:
        cache-name: cache-eggs
      with:
        path: ./eggs
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and run buildout
      run: |
        sudo apt-get install -qq -y python3-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt coveralls==3.2.0
        buildout -Nt 5

    - name: Coverage test
      run: |
        coverage run bin/test

    - name: Submit to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github

