name: Tests

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: IMIO/gha/.github/workflows/package-test.yml@reusable-workflows
    strategy:
      matrix:
        python_version: ['3.8', '3.9']
        plone_version: ['6']
    with:
      branch_name: main
      runner_label: gha-runners-smartweb
      soffice: false
      test_command: 'TZ=UTC bin/test'
      python_version: ${{ matrix.python_version }}
      plone_version: ${{ matrix.plone_version }}
    secrets: inherit