name: Tests

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: gha-runners-smartweb
    strategy:
      matrix:
        python-version: ['3.10', '3.13']
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4
    - name: Run check
      uses: IMIO/gha/plone-package-test-notify@v5
      with:
        BUILDOUT_COMMAND: .venv/bin/buildout
        CACHE_KEY: eggs-test-${{ hashFiles('base.cfg') }}-python-${{ matrix.python-version }}
        INSTALL_DEPENDENCIES_COMMANDS: |
          uv venv --python ${{ matrix.python-version }} --managed-python
          uv pip install -r requirements.txt
        MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
        PYTHON_VERSION: ${{ matrix.python-version }}
        TEST_COMMAND: TZ=UTC bin/test

  coverage:
    runs-on: gha-runners-smartweb
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4
    - name: Run check
      uses: IMIO/gha/plone-package-test-notify@v3.9.4
      with:
        CACHE_KEY: eggs-test-${{ hashFiles('base.cfg') }}-python-3.10
        TEST_COMMAND: TZ=UTC coverage run bin/test
        REQUIREMENTS_FILE: 'requirements-coverage.txt'
        MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
    - name: Submit to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github


    uses: IMIO/gha/.github/workflows/package-test.yml@reusable-workflows
    strategy:
      matrix:
        python_version: ['3.8', '3.9']
        plone_version: ['6']
    with:
      branch_name: main
      runner_label: gha-runners-smartweb
      soffice: false
      test_command: 'TZ=UTC bin/test'
      python_version: ${{ matrix.python_version }}
      plone_version: ${{ matrix.plone_version }}
      install_dependencies_commands: 'sudo pip install -r requirements.txt'
    secrets: inherit
