name: Tests

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  full-test:
    uses: IMIO/gha-workflows/.github/workflows/package-full-test.yml@v1
    secrets:
      mattermost_webhook_url: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
    with:
      check_path: |
        imio/smartweb/core
      buildout_config_file: test_plone6.cfg
      python_versions: '["3.12", "3.13"]'
      runner_label: gha-runners-smartweb
      test_command: TZ=UTC bin/test
      upload_to_coveralls: true
