name: Tests

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: IMIO/gha/.github/workflows/package-test.yml@reusable-workflows
    with:
      branch_name: main
      python_version: '3.8, 3.9, 3.10'
      plone_version: 6
      runner_label: gha-runners-smartweb
      soffice: false
      test_command: 'TZ=UTC bin/test'
    secrets: inherit