name: Tests

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # black:
  #   runs-on: gha-runners-smartweb
  #   steps:
  #   - name: Checkout codebase
  #     uses: actions/checkout@v4
  #   - name: Run check
  #     uses: IMIO/gha/code-analysis-notify@v3.9.4
  #     with:
  #       BASE_DIR: 'src'
  #       CHECK: 'black'
  #       PATH: |
  #         imio/smartweb/core
  #       MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}

  test:
    uses: IMIO/gha-workflows/.github/workflows/package-test-uv.yml@main
    strategy:
      matrix:
        python_version: ['3.10']
        plone_version: ['6.1']
    with:
      buildout_config_file: gha_${{ matrix.plone_version }}.cfg
      buildout_command: '.venv/bin/buildout'
      continue_on_error: false
      plone_version: ${{ matrix.plone_version }}
      python_version: ${{ matrix.python_version }}
      runner_label: gha-runners-smartweb
      soffice: false
      test_command: 'TZ=UTC bin/test'
    secrets: inherit

  # coverage:
  #   runs-on: gha-runners-smartweb
  #   steps:
  #   - name: Checkout codebase
  #     uses: actions/checkout@v4
  #   - name: Run check
  #     uses: IMIO/gha/plone-package-test-notify@v3.9.4
  #     with:
  #       CACHE_KEY: eggs-test-${{ hashFiles('base.cfg') }}-python-3.10
  #       TEST_COMMAND: TZ=UTC coverage run bin/test
  #       REQUIREMENTS_FILE: 'requirements-coverage.txt'
  #       MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
  #   - name: Submit to Coveralls
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: coveralls --service=github
